import type { TableColumnsType } from 'ant-design-vue';
import {numberWithComma, formatDateTime, numberWithCommaIdr} from '../../../../common/utils/format';

export const detailColumns: TableColumnsType = [
    { title: 'ID', dataIndex: 'id'},
    { title: 'Vessel ID', dataIndex: 'vesselId'},
    { title: 'Captain ID', dataIndex: 'captainId'},
    { title: 'Cargo', dataIndex: 'cargo', customRender: numberWithComma},
    { title: 'Diesel', dataIndex: 'diesel', customRender: numberWithComma},
    { title: 'Distance', dataIndex: 'distance', customRender: numberWithComma},
    { title: 'Origin Port ID', dataIndex: 'originPortId'},
    { title: 'Order Status', dataIndex: 'orderStatus'},
    { title: 'Origin To Destination Speed', dataIndex: 'originToDestinationSpeed'},
    { title: 'Origin Loading Rate', dataIndex: 'originLoadingRate', customRender: numberWithComma},
    { title: 'Origin Idle Day', dataIndex: 'originIdleDay'},
    { title: 'Destination Port ID', dataIndex: 'destinationPortId'},
    { title: 'Destination To Origin Speed', dataIndex: 'destinationToOriginSpeed' },
    { title: 'Destination Discharge Rate', dataIndex: 'destinationDischargeRate', customRender: numberWithComma},
    { title: 'Destination Idle Day', dataIndex: 'destinationIdleDay'},
    { title: 'TC Cost', dataIndex: 'tcCost', customRender: numberWithCommaIdr},
    { title: 'Initial Freight', dataIndex: 'initialFreight'},
    { title: 'Created At', dataIndex: 'createdAt', customRender: formatDateTime },
    { title: 'Created By', dataIndex: 'createdBy', customRender: formatDateTime },
    { title: 'Modified By', dataIndex: 'modifiedBy', customRender: formatDateTime },
    { title: 'Modified At', dataIndex: 'modifiedAt', customRender: formatDateTime },
    { title: 'Origin To Destination Day', dataIndex: 'originToDestinationDay'},
    { title: 'Destination To Origin Day', dataIndex: 'destinationToOriginDay' },
    { title: 'Total Distance', dataIndex: 'totalDistance'},
    { title: 'Total Sail Day', dataIndex: 'totalSailDay'},
    { title: 'Total Working Day', dataIndex: 'totalWorkingDay'},
    { title: 'Origin Loading Day', dataIndex: 'originLoadingDay'},
    { title: 'Destination Discharge Day', dataIndex: 'destinationDischargeDay'},
    { title: 'Total Days', dataIndex: 'totalDays'},
    { title: 'Total ME Fuel On Ballast', dataIndex: 'totalMeFuelOnBallast', customRender: numberWithCommaIdr },
    { title: 'Total ME Fuel Cost On Ballast', dataIndex: 'totalMeFuelCostOnBallast', customRender: numberWithCommaIdr },
    { title: 'Total ME Fuel On Laden', dataIndex: 'totalMeFuelOnLaden', customRender: numberWithCommaIdr },
    { title: 'Total ME Fuel Cost On Laden', dataIndex: 'totalMeFuelCostOnLaden', customRender: numberWithCommaIdr },
    { title: 'Total ME Fuel', dataIndex: 'totalMeFuel', customRender: numberWithComma },
    { title: 'Total ME Fuel Cost', dataIndex: 'totalMeFuelCost', customRender: numberWithCommaIdr},
    { title: 'Total AE Fuel On Origin Idle', dataIndex: 'totalAeFuelOnOriginIdle', customRender: numberWithComma },
    { title: 'Total AE Fuel Cost On Origin Idle', dataIndex: 'totalAeFuelCostOnOriginIdle', customRender: numberWithCommaIdr },
    { title: 'Total AE Fuel On Origin Loading', dataIndex: 'totalAeFuelOnOriginLoading', customRender: numberWithComma },
    { title: 'Total AE Fuel Cost On Origin Loading', dataIndex: 'totalAeFuelCostOnOriginLoading', customRender: numberWithCommaIdr },
    { title: 'Total AE Fuel On Destination Idle', dataIndex: 'totalAeFuelOnDestinationIdle', customRender: numberWithCommaIdr },
    { title: 'Total AE Fuel Cost On Destination Idle', dataIndex: 'totalAeFuelCostOnDestinationIdle', customRender: numberWithCommaIdr },
    { title: 'Total AE Fuel On Destination Discharge', dataIndex: 'totalAeFuelOnDestinationDischarge'},
    { title: 'Total AE Fuel Cost On Destination Discharge', dataIndex: 'totalAeFuelCostOnDestinationDischarge', customRender: numberWithCommaIdr },
    { title: 'Total AE Fuel', dataIndex: 'totalAeFuel'},
    { title: 'Total AE Fuel Cost', dataIndex: 'totalAeFuelCost', customRender: numberWithCommaIdr},
    { title: 'Total Fuel', dataIndex: 'totalFuel', customRender: numberWithComma},
    { title: 'Total Fuel Cost', dataIndex: 'totalFuelCost', customRender: numberWithCommaIdr},
    { title: 'Port Disbursements Map', dataIndex: 'portDisbursementsMap', customRender: numberWithComma},
    { title: 'Port Disbursements Total', dataIndex: 'portDisbursementsTotal'},
    { title: 'TC Cost Monthly', dataIndex: 'tcCostMonthly', customRender: numberWithCommaIdr},
    { title: 'Total Cost', dataIndex: 'totalCost', customRender: numberWithCommaIdr},
    { title: 'Total BEP', dataIndex: 'totalBep', customRender: numberWithComma},
    { title: 'Total Initial Freight', dataIndex: 'totalInitialFreight', customRender: numberWithCommaIdr},
    { title: 'Total Initial Margin', dataIndex: 'totalInitialMargin', customRender: numberWithCommaIdr},
    { title: 'Operator', key: 'operation', fixed: 'right'},
];

export const orderColumns: TableColumnsType = [
    {dataIndex: 'id', title: 'ID'},
    { title: 'Origin Port ID', dataIndex: 'originPortId'},
    { title: 'Destination Port ID', dataIndex: 'destinationPortId'},
    { title: 'Total Distance', dataIndex: 'totalDistance'},
    { title: 'Total Sail Day', dataIndex: 'totalSailDay'},
    { title: 'Total Working Day', dataIndex: 'totalWorkingDay' },
    { title: 'Total ME Fuel', dataIndex: 'totalMeFuel', customRender: numberWithCommaIdr},
    { title: 'Total ME Fuel Cost', dataIndex: 'totalMeFuelCost', customRender: numberWithCommaIdr},
    { title: 'Total AE Fuel', dataIndex: 'totalAeFuel', customRender: numberWithComma},
    { title: 'Total AE Fuel Cost', dataIndex: 'totalAeFuelCost', customRender: numberWithCommaIdr},
    { title: 'TC Cost Monthly', dataIndex: 'tcCostMonthly', customRender: numberWithCommaIdr},
    { title: 'Total Cost', dataIndex: 'totalCost', customRender: numberWithCommaIdr},
    { title: 'Total BEP', dataIndex: 'totalBep', customRender: numberWithComma},
    { title: 'Total Days', dataIndex: 'totalDays'},
    { title: 'Created At', dataIndex: 'createdAt', customRender: formatDateTime},
    { title: 'Created By', dataIndex: 'createdBy' },
    { title: 'Modified By', dataIndex: 'modifiedBy' },
    { title: 'Modified At', dataIndex: 'modifiedAt', customRender: formatDateTime},
    { title: 'TC Cost', dataIndex: 'tcCost', customRender: numberWithCommaIdr},
    { title: 'Operator', key: 'operation', fixed: 'right'},
]
